Verify zk onchain
Unirep/Unirep pull request #110
Opened 2022-08-12 11:02 UTC by vivianjeng

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #101 

## What is the new behavior?

- Verify proofs before assigning proof index
- 
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-08-13 12:50 UTC, vimwitch requested changes

2022-08-13 12:50 UTC, vimwitch commented on packages/contracts/contracts/Unirep.sol
> +    function verifyProof(bool isValid) private pure {
This doesn't need to be a function.

2022-08-13 12:50 UTC, vimwitch commented on packages/contracts/contracts/Unirep.sol
> +=======
merge conflict marker

2022-08-15 12:14 UTC, vimwitch approved these changes

2022-08-15 12:30 UTC, vuvoth approved these changes

2022-08-15 12:30 UTC, vuvoth commented on packages/core/test/utils.ts
> +// const genReputationCircuitInput = (
Let remove it if we don't use it

2022-08-15 12:30 UTC, vuvoth commented on packages/core/test/UserState/reputationProofEvent.test.ts
> +                BigInt(Math.floor(Math.random() * 0)),
BigInt(Math.floor(Math.random() * 0)) always return 0,right?

2022-08-15 13:06 UTC, merged