Add contracts tests
Unirep/Unirep pull request #125
Opened 2022-08-29 06:38 UTC by vivianjeng

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

## What is the new behavior?

- closes #114 
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-08-29 23:41 UTC, vimwitch commented on packages/contracts/test/userStateTransition.test.ts
> +    const user = new ZkIdentity()
This doesn't need to be a shared variable.

2022-08-29 23:41 UTC, vimwitch commented on packages/contracts/test/userStateTransition.test.ts
> +import { ethers } from 'ethers'
These don't need to be separate variables. `hardhatEthers` is a superset of ethers.

2022-08-29 23:41 UTC, vimwitch commented on packages/contracts/test/userStateTransition.test.ts
> +    let accounts: ethers.Signer[]
This doesn't need to be a global variable either.

2022-08-29 23:41 UTC, vimwitch commented on packages/contracts/test/userStateTransition.test.ts
> +    let epoch = 1
This should be loaded from the contract instead of being defined here.

2022-08-29 23:41 UTC, vimwitch commented on packages/contracts/test/userStateTransition.test.ts
> +        unirepContract.beginEpochTransition().then((t) => t.wait())
Make sure to `await this`

2022-08-29 23:47 UTC, vimwitch requested changes
I think we need tests for the attestation functions checking the GST and epoch tree as attestations are made. We also need tests to make sure that zk proofs are verified and nullifiers are recorded as spent (when spending rep).

2022-08-29 23:47 UTC, vimwitch commented on packages/contracts/test/userStateTransition.test.ts
> +            unirepContract
All of these need to be awaited. Using `.then` causes a chained promise to be returned, we still need to wait for the chained promise.

2022-08-29 23:47 UTC, vimwitch commented on packages/contracts/test/userStateTransition.test.ts
> +        } = genUserStateTransitionCircuitInput(user2, epoch)
I think this needs an `await`?

2022-08-29 23:47 UTC, vimwitch commented on packages/contracts/test/userStateTransition.test.ts
> +        epoch++
Definitely want to load this from the contract

2022-08-29 23:58 UTC, vimwitch commented
I see #126 has tests for attestations/epoch trees. Might be good to have GST tests here

2022-09-02 09:43 UTC, vivianjeng commented on packages/contracts/test/userStateTransition.test.ts
> +        } = genUserStateTransitionCircuitInput(user2, epoch)
no because it doesn't generate proofs

2022-09-06 03:49 UTC, vimwitch approved these changes
lgtm

2022-09-06 06:17 UTC, merged