feat: graffiti support
Unirep/Unirep pull request #149
Opened 2022-10-15 19:42 UTC by vimwitch

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Closes #148 

## What is the new behavior?

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-10-20 04:14 UTC, vivianjeng reviewed
I think the functions in `Synchronizer` and `UserState` should be covered in tests
e.g. check if `Synchronizer` saves event correctly, trees are correctly generated, `UserState` can generate correct proofs...

2022-10-20 15:19 UTC, vimwitch commented on packages/contracts/test/userStateTransition.test.ts
>                  .to.emit(unirepContract, 'UserStateTransitioned')
This is tested in the core package. But we need more tests for everything

2022-10-23 17:53 UTC, vivianjeng requested changes
There is still a `globalStateTree` function
https://github.com/Unirep/Unirep/blob/3273d920d419cc82e84c54f3181b325418123fde/packages/core/src/Synchronizer.ts#L30

and there are still some `GST` are not changes in this PR

2022-10-23 17:53 UTC, vivianjeng commented on packages/contracts/scripts/deploy.mjs
> +})
now the settings are
```ts
{
        stateTreeDepth?: BigNumberish
        epochTreeDepth?: BigNumberish
        numEpochKeyNoncePerEpoch?: BigNumberish
        emptyEpochTreeRoot?: BigNumberish
    }
```

2022-10-23 18:01 UTC, vimwitch commented
Ok, should be fixed

2022-10-23 18:20 UTC, vivianjeng commented
Search for `GST` there are still many variables remained
https://github.com/Unirep/Unirep/blob/280b443208e86c75322fedda01ec5cb3bb1df7b1/packages/core/src/UserState.ts#L173

https://github.com/Unirep/Unirep/blob/3273d920d419cc82e84c54f3181b325418123fde/packages/core/src/Synchronizer.ts#L32

https://github.com/Unirep/Unirep/blob/280b443208e86c75322fedda01ec5cb3bb1df7b1/packages/circuits/test/utils.ts#L287

Can you check them in your local?
Since they are not in the pr

2022-10-23 18:35 UTC, vimwitch commented
Ok all instances should be fixed

2022-10-23 19:17 UTC, vivianjeng commented
https://github.com/Unirep/Unirep/blob/d1f3c4b87f6dff0b6301bf38ba82de60d808c497/packages/circuits/test/utils.ts#L351

https://github.com/Unirep/Unirep/blob/d1f3c4b87f6dff0b6301bf38ba82de60d808c497/packages/core/src/Synchronizer.ts#L81

some comments still remain.
we don't need the type of `circuitInput`?
I think we can maintain it so in `@unirep/circuits` and `@unirep/core` we can more easily create circuitInputs and don't need to look at circom files

2022-10-23 19:37 UTC, vimwitch commented
We don't use the ts definitions in the prover implementations. I think we can re-add them later, but for now we can use the [docs](https://developer.unirep.io/docs/circuits-api/circuits#user-state-transition-proof).

> some comments still remain.

I think it's okay for now, we can remove them as we go.

2022-10-23 19:52 UTC, vivianjeng approved these changes

2022-10-23 19:55 UTC, merged