Make `from_epoch` a private signal in the UST
Unirep/Unirep pull request #342
Opened 2023-02-23 21:23 UTC by vimwitch

fix(circuits): make from_epoch a private input

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## Other information

2023-03-21 23:49 UTC, vimwitch commented on packages/contracts/deploy/deploy.ts
> +    await PoseidonT3.deployed()
I think if there are more than 3 it makes sense it iterate, but for just 2 the current is okay

2023-03-22 00:21 UTC, vimwitch commented
So in the current implementation `updateEpochIfNeeded` must be called for the epoch the user is transitioning from. This must happen so that the `HistoryTreeLeaf` event will be emitted and the proof can be calculated.

Once we have #350 we can update the latest history tree leaf any time the state tree is updated. This way the `updateEpochIfNeeded` function doesn't need to do the empty epoch seal logic. Anytime the state tree is changed the latest history tree leaf will be changed. If an attestation occurs the leaf will be zeroed (so the a user cannot transition with 0 rep).

When a previous epoch is sealed we can remove the latest leaf, insert the sealed leaf, then re-insert the latest leaf. We'll need to figure out how to handle the events for this.

I think for now requiring the attester to call `updateEpochIfNeeded` manually is an okay requirement. #350 should be done in the next week to fix this problem. There's also an optimistic approach to calculating the history leaf in #359. This approach will fail if a different epoch is sealed between when the proof is calculated and broadcasted.

2023-03-24 08:15 UTC, vivianjeng reviewed
https://github.com/Unirep/Unirep/blob/4ea2a43e9fb4dfe323e8a42d8f4f2347caace796/packages/contracts/contracts/Unirep.sol#L376-L377
I think we should note that it is an history tree root
and we should document it in protocol/trees

2023-03-24 09:02 UTC, vivianjeng requested changes

2023-03-24 09:02 UTC, vivianjeng commented on packages/contracts/contracts/Unirep.sol
> +        uint oldEpoch = attester.currentEpoch;
I think it should take the `oldEpoch` state
```solidity
uint oldEpoch = attester.currentEpoch;
AttesterState storage state = attester.state[oldEpoch];
```

2023-04-06 06:46 UTC, vimwitch commented
Closing in favor of #386

2023-04-06 06:46 UTC, closed without merging